CREATE TABLE DEPT2
(DEPTNO NUMBER(10) CONSTRAINT DEPT2_DEPNO_PK PRIMARY KEY,
 DNAME VARCHAR2(14),
 LOC VARCHAR2(10));
 
 CREATE TABLE DEPT3
 (DEPTNO NUMBER(10),
  DNAME VARCHAR2(14) CONSTRAINT DEPT3_DNAME_UN UNIQUE,
  LOC VARCHAR2(10));
  
CREATE TABLE DEPT4
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(13),
 LOC VARCHAR2(10));
 
 ALTER TABLE DEPT4
    ADD CONSTRAINT DEPT4_DNAME_UN UNIQUE(DNAME);
    
CREATE TABLE DEPT5
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(10) CONSTRAINT DEPT5_LOC_NN NOT NULL);
 
 CREATE TABLE DEPT6
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(10));
 
 ALTER TABLE DEPT6
    MODIFY LOC CONSTRAINT DEPT6_LOC_NN NOT NULL;
    
CREATE TABLE EMP6
( EMPNO NUMBER(10),
  ENAME VARCHAR2(20),
  SAL NUMBER(10) CONSTRAINT EMP6_SAL_CK
  CHECK ( SAL BETWEEN 0 AND 6000) );